name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy-reverse-proxy:
    name: Push custom Nginx reverse proxy Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.4
      - name: Build and push Docker images to GitHub Packages
        uses: docker/build-push-action@v2.1.0
        with:
          tags: nginx-reverse-proxy
          file: ./nginx/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: jftung/docker-network/jenkins-host
  deploy-certbot:
    name: Push custom Certbot Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.4
      - name: Build and push Docker images to GitHub Packages
        uses: docker/build-push-action@v2.1.0
        with:
          tags: certbot-beale
          file: ./certbot/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: jftung/docker-network/jenkins-host
  deploy-beale:
    name: Push custom Nginx Beale website Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.4
      - name: Build and push Docker images to GitHub Packages
        uses: docker/build-push-action@v2.1.0
        with:
          tags: nginx-beale
          file: ./Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: jftung/docker-network/jenkins-host
  deploy-jenkins-host:
    name: Push custom Jenkins Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.4
      - name: Build and push Docker images to GitHub Packages
        uses: docker/build-push-action@v2.1.0
        with:
          tags: jenkins-host
          file: ./jenkins/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: jftung/docker-network/jenkins-host
