name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy-reverse-proxy:
    name: Build and push Docker images to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.0.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Nginx reverse proxy Docker image to GitHub Packages
        uses: docker/build-push-action@v2.1.0
        with:
          tags: |
            nginx-reverse-proxy:latest
            jftung/nginx-reverse-proxy:latest
            ghcr.io/jftung/nginx-reverse-proxy:latest
          file: ./nginx/reverse-proxy/Dockerfile
          push: true

      - name: Build and push custom Certbot Docker image to GitHub Packages
        uses: docker/build-push-action@v2.1.0
        with:
          tags: |
            certbot-beale:latest
            jftung/certbot-beale:latest
            ghcr.io/jftung/certbot-beale:latest
          file: ./certbot/Dockerfile
          push: true

      - name: Build and push Nginx Beale website Docker image to GitHub Packages
        uses: docker/build-push-action@v2.1.0
        with:
          tags: |
            nginx-beale:latest
            jftung/nginx-beale:latest
            ghcr.io/jftung/nginx-beale:latest
          file: ./nginx/beale/Dockerfile
          push: true

      - name: Build and push custom Jenkins Docker image to GitHub Packages
        uses: docker/build-push-action@v2.1.0
        with:
          tags: |
            jenkins-host:latest
            jftung/jenkins-host:latest
            ghcr.io/jftung/jenkins-host:latest
          file: ./jenkins/Dockerfile
          push: true
